# Generated by Django 3.1.1 on 2020-09-02 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='student1',
        ),
    ]
